/**
 * AI liability disclaimer footer.
 * Rendered at the bottom of simulation results pages and public share pages.
 */
export function DisclaimerFooter() {
  return (
    <div className="mt-8 pt-6 border-t border-border text-center">
      <p className="text-xs text-muted-foreground max-w-2xl mx-auto leading-relaxed">
        These simulations are generated by AI for educational purposes only.
        They do not constitute financial, legal, or business advice.
        Past simulated outcomes do not predict future results.
      </p>
    </div>
  );
}
