"""ReportLab PDF generator for pre-mortem reports."""
from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

DISCLAIMER = (
    "DISCLAIMER: This pre-mortem analysis is generated by an AI simulation engine and is provided "
    "for strategic planning purposes only. It does not constitute legal, financial, or investment advice. "
    "Founder Fate and its operators make no representations or warranties regarding the accuracy, "
    "completeness, or fitness for purpose of this report. Founders should consult qualified advisors "
    "before making material business decisions."
)


def generate_pdf(report: dict, output_path: Path) -> Path:
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=1.5 * inch,
    )
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle("FFTitle", parent=styles["Title"], fontSize=24, spaceAfter=12)
    heading_style = ParagraphStyle(
        "FFHeading", parent=styles["Heading2"], fontSize=14, spaceBefore=16, spaceAfter=8
    )
    body_style = ParagraphStyle("FFBody", parent=styles["Normal"], fontSize=10, spaceAfter=6)
    disclaimer_style = ParagraphStyle(
        "FFDisclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.gray,
        spaceAfter=6,
    )

    synthesis = report.get("synthesis", {})
    iterations = report.get("iterations", [])

    story = []

    # Header
    story.append(Paragraph("Founder Fate — Pre-Mortem Analysis", title_style))
    story.append(
        Paragraph(f"Scenario: {report.get('scenario_name', 'Unknown')}", styles["Heading3"])
    )
    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.black))
    story.append(Spacer(1, 12))

    # Executive Summary
    story.append(Paragraph("Executive Summary", heading_style))
    story.append(
        Paragraph(synthesis.get("executive_summary", "No summary available."), body_style)
    )

    # Overall risk score
    risk_score = synthesis.get("overall_risk_score", 0.5)
    verdict = synthesis.get("verdict", "moderate_risk").replace("_", " ").title()
    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            f"<b>Overall Risk Score:</b> {float(risk_score):.0%} — {verdict}", body_style
        )
    )

    # Top Risks
    story.append(Paragraph("Top Risks Identified", heading_style))
    for i, risk in enumerate(synthesis.get("top_risks", []), 1):
        story.append(Paragraph(f"{i}. {risk}", body_style))

    # Recommended Actions
    story.append(Paragraph("Recommended Actions", heading_style))
    for i, action in enumerate(synthesis.get("recommended_actions", []), 1):
        story.append(Paragraph(f"{i}. {action}", body_style))

    # Failure Mode Analysis Table
    story.append(Paragraph("Failure Mode Analysis", heading_style))
    if iterations:
        table_data = [["Failure Mode", "Probability", "Severity", "Timeline"]]
        for row in iterations:
            table_data.append([
                Paragraph(row["failure_mode"][:80], body_style),
                f"{float(row['probability']):.0%}",
                row["severity"].title(),
                f"{row['timeline_months']}mo",
            ])

        table = Table(table_data, colWidths=[3.5 * inch, 1 * inch, 1 * inch, 1 * inch])
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#f8fafc")],
                ),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ])
        )
        story.append(table)

    # Mitigations
    story.append(Paragraph("Mitigation Strategies", heading_style))
    for row in iterations[:5]:  # Top 5 mitigations
        story.append(
            Paragraph(
                f"<b>{row['failure_mode'][:60]}:</b> {row['mitigation']}", body_style
            )
        )

    # Disclaimer footer
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.gray))
    story.append(Spacer(1, 8))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))

    doc.build(story)
    return output_path
