import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Founder Fate",
  description: "Founder Fate terms of service — the agreement between you and Founder Fate, Inc.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-4 py-16 space-y-10">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
          <p className="text-muted-foreground mt-2 text-sm">
            Last updated: May 27, 2026
          </p>
        </div>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-10 text-sm leading-relaxed">

          {/* 1. Acceptance */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing or using Founder Fate (&ldquo;the Service&rdquo;), operated by
              Founder Fate, Inc. (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you agree to be bound by these
              Terms of Service (&ldquo;Terms&rdquo;). If you are using the Service on behalf of an
              organisation, you represent that you have authority to bind that organisation
              to these Terms.
            </p>
            <p className="text-muted-foreground">
              If you do not agree to these Terms, do not use the Service. These Terms
              apply in addition to any other agreements you enter with us, such as a
              Data Processing Agreement.
            </p>
          </section>

          {/* 2. Service Description */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">2. Service Description</h2>
            <p className="text-muted-foreground">
              Founder Fate is an AI-powered consequence simulation platform designed to
              help founders explore the potential downstream effects of high-stakes
              decisions — such as hiring, fundraising, pricing, and pivots — before
              committing to them.
            </p>
            <p className="text-muted-foreground">
              <strong className="text-foreground">Important:</strong> Simulations are
              generated by large language models and are intended for educational and
              reflective purposes only. They are not financial advice, legal advice,
              business advice, or predictions of future events. Founder Fate, Inc.
              makes no representations about the accuracy, completeness, or reliability
              of any simulation output. You should consult qualified professionals before
              making significant business decisions.
            </p>
          </section>

          {/* 3. User Accounts */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">3. User Accounts</h2>
            <p className="text-muted-foreground">
              You must be at least 18 years old to create an account. By creating an
              account you confirm that you meet this age requirement. We enforce an age
              gate during onboarding.
            </p>
            <p className="text-muted-foreground">
              You are responsible for maintaining the confidentiality of your account
              credentials and for all activity that occurs under your account. Notify us
              immediately at{" "}
              <a href="mailto:support@founderfate.ai" className="text-primary underline underline-offset-2">
                support@founderfate.ai
              </a>{" "}
              if you suspect unauthorised access.
            </p>
            <p className="text-muted-foreground">
              You may not create multiple accounts to circumvent usage limits or
              suspension decisions. One account per person is permitted on the Free plan.
            </p>
          </section>

          {/* 4. Acceptable Use */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">4. Acceptable Use</h2>
            <p className="text-muted-foreground">You agree not to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>
                Use automated tools to scrape, crawl, or systematically extract content
                from the Service, including simulation outputs or consequence trees.
              </li>
              <li>
                Attempt to extract, reverse-engineer, or reconstruct any underlying AI
                model training data, weights, or prompts.
              </li>
              <li>
                Use the Service to generate content that is unlawful, harmful, harassing,
                defamatory, or that infringes any third-party rights.
              </li>
              <li>
                Probe, scan, or test the vulnerability of the Service or attempt to
                bypass any security or authentication mechanism.
              </li>
              <li>
                Resell, sublicense, or commercially redistribute the Service or
                simulation outputs without our express written consent.
              </li>
              <li>
                Use the Service in any way that violates applicable laws or regulations,
                including export control laws.
              </li>
            </ul>
            <p className="text-muted-foreground">
              We reserve the right to investigate suspected violations and to suspend or
              terminate accounts that breach these rules.
            </p>
          </section>

          {/* 5. Subscription and Billing */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">5. Subscription and Billing</h2>
            <p className="text-muted-foreground">
              Founder Fate offers a Free tier and paid subscription plans (&ldquo;Pro&rdquo;,
              &ldquo;Enterprise&rdquo;). Paid plans are billed monthly or annually through Stripe.
              All prices are in US dollars unless otherwise stated. Taxes may apply
              depending on your location.
            </p>
            <p className="text-muted-foreground">
              Free tier users are subject to usage limits (e.g., maximum number of
              simulations per month). Exceeding these limits may require upgrading to
              a paid plan.
            </p>
            <p className="text-muted-foreground">
              Subscriptions renew automatically unless cancelled before the renewal date.
              You can cancel at any time from your{" "}
              <Link href="/billing" className="text-primary underline underline-offset-2">
                billing settings
              </Link>
              . Cancellation takes effect at the end of the current billing period; no
              pro-rated refunds are issued for partial periods except as required by law.
            </p>
            <p className="text-muted-foreground">
              <strong className="text-foreground">Refund policy:</strong> If you are
              unsatisfied with a paid plan, you may request a full refund within 7 days
              of your first payment on that plan by contacting{" "}
              <a href="mailto:support@founderfate.ai" className="text-primary underline underline-offset-2">
                support@founderfate.ai
              </a>
              . After 7 days, refunds are issued at our discretion.
            </p>
          </section>

          {/* 6. Intellectual Property */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">6. Intellectual Property</h2>
            <p className="text-muted-foreground">
              <strong className="text-foreground">Your content:</strong> Simulation inputs
              you provide and the AI-generated outputs you receive are your work product.
              You retain ownership of your inputs. You also own the outputs generated on
              your behalf, subject to the limitations of applicable AI model licenses.
              We grant you a perpetual, royalty-free licence to use, copy, and distribute
              your simulation outputs for any lawful purpose.
            </p>
            <p className="text-muted-foreground">
              <strong className="text-foreground">Our IP:</strong> The Founder Fate
              platform, brand, software, scenario templates, and Decision DNA methodology
              are our intellectual property. You may not copy, modify, create derivative
              works of, or distribute any part of the platform without our written consent.
            </p>
            <p className="text-muted-foreground">
              <strong className="text-foreground">Feedback:</strong> If you submit
              feedback or suggestions about the Service, you grant us a royalty-free
              licence to use that feedback without restriction or compensation.
            </p>
          </section>

          {/* 7. Disclaimers */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">7. Disclaimers</h2>
            <p className="text-muted-foreground">
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF
              ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p className="text-muted-foreground">
              AI SIMULATION OUTPUTS ARE NOT PREDICTIONS. They are probabilistic
              explorations generated by language models and may contain errors, biases,
              or outdated information. We do not warrant the accuracy, completeness, or
              reliability of any simulation result. Reliance on simulation outputs for
              actual business decisions is entirely at your own risk.
            </p>
            <p className="text-muted-foreground">
              We do not warrant that the Service will be uninterrupted, error-free, or
              free from viruses or other harmful components.
            </p>
          </section>

          {/* 8. Limitation of Liability */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">8. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, FOUNDER FATE, INC.
              AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE
              FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
              INCLUDING LOST PROFITS, LOSS OF DATA, OR BUSINESS INTERRUPTION, ARISING
              OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF WE HAVE
              BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="text-muted-foreground">
              IN ALL CASES OUR TOTAL AGGREGATE LIABILITY TO YOU SHALL NOT EXCEED THE
              GREATER OF (A) THE FEES YOU HAVE PAID TO US IN THE THREE MONTHS IMMEDIATELY
              PRECEDING THE CLAIM, OR (B) ONE HUNDRED US DOLLARS ($100).
            </p>
            <p className="text-muted-foreground">
              Some jurisdictions do not allow the exclusion or limitation of certain
              damages; in those cases our liability is limited to the minimum extent
              permitted by law.
            </p>
          </section>

          {/* 9. Termination */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">9. Termination</h2>
            <p className="text-muted-foreground">
              We may suspend or terminate your access to the Service at any time, with
              or without notice, if we reasonably believe you have violated these Terms
              or applicable law. We will attempt to provide advance notice when
              practicable except where immediate termination is required to protect the
              Service or other users.
            </p>
            <p className="text-muted-foreground">
              You may close your account at any time from your profile settings. Upon
              account deletion we will remove your personal data in accordance with our{" "}
              <Link href="/privacy" className="text-primary underline underline-offset-2">
                Privacy Policy
              </Link>
              . EU/UK residents may request erasure under GDPR by emailing{" "}
              <a href="mailto:privacy@founderfate.ai" className="text-primary underline underline-offset-2">
                privacy@founderfate.ai
              </a>
              .
            </p>
          </section>

          {/* 10. Governing Law */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">10. Governing Law</h2>
            <p className="text-muted-foreground">
              These Terms are governed by and construed in accordance with the laws of
              the State of Delaware, USA, without regard to its conflict of law provisions.
              You agree to submit to the exclusive jurisdiction of the state and federal
              courts located in Delaware for resolution of any dispute arising under
              these Terms, subject to the arbitration clause below.
            </p>
            <p className="text-muted-foreground">
              For users in the European Union, nothing in these Terms affects your rights
              under EU consumer protection law, including the right to bring claims before
              your local courts.
            </p>
          </section>

          {/* 11. Changes */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">11. Changes to These Terms</h2>
            <p className="text-muted-foreground">
              We reserve the right to modify these Terms at any time. For material
              changes we will provide at least 30 days&rsquo; notice before the new Terms
              take effect, via email and an in-app notification. Your continued use of
              the Service after the effective date constitutes acceptance of the updated
              Terms.
            </p>
            <p className="text-muted-foreground">
              If you do not agree to the updated Terms, you must stop using the Service
              before the effective date. If you have a paid subscription, you may cancel
              within the notice period for a pro-rated refund of any prepaid fees.
            </p>
          </section>

          {/* 12. Contact */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">12. Contact</h2>
            <p className="text-muted-foreground">
              If you have questions about these Terms, please contact:
            </p>
            <div className="rounded-lg border border-border bg-muted/30 p-4 space-y-1">
              <p className="text-sm font-medium text-foreground">Founder Fate, Inc.</p>
              <p className="text-sm text-muted-foreground">San Francisco, CA, USA</p>
              <a href="mailto:legal@founderfate.ai" className="text-sm text-primary underline underline-offset-2">
                legal@founderfate.ai
              </a>
            </div>
          </section>

        </div>

        <p className="text-xs text-muted-foreground border-t border-border pt-4 flex gap-4">
          <Link href="/" className="hover:text-foreground transition-colors">
            &larr; Back to Founder Fate
          </Link>
          <Link href="/privacy" className="hover:text-foreground transition-colors">
            Privacy Policy
          </Link>
          <Link href="/cookies" className="hover:text-foreground transition-colors">
            Cookie Policy
          </Link>
        </p>
      </div>
    </div>
  );
}
